/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikerental;

/**
 *
 * @author firstx
 */
public class FormRent extends javax.swing.JFrame {

    /**
     * Creates new form FormRent
     */
    public FormRent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        labelShowDate = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBikeStatus = new javax.swing.JTable();
        labelRentId = new javax.swing.JLabel();
        labelRentDate = new javax.swing.JLabel();
        labelCitizenId = new javax.swing.JLabel();
        btnRent = new javax.swing.JButton();
        labelFName = new javax.swing.JLabel();
        labelBikeId = new javax.swing.JLabel();
        labelLName = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelReturnDate = new javax.swing.JLabel();
        labelFee = new javax.swing.JLabel();
        txtRentId = new javax.swing.JTextField();
        txtRentDate = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        txtFee = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtCitizenId = new javax.swing.JTextField();
        txtBikeId = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuIncome = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setMinimumSize(new java.awt.Dimension(900, 600));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        labelName.setText("RENTAL CARS");
        head.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        labelShowTime.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowTime.setText("HH:MM:SS A");
        head.add(labelShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/R (1).png"))); // NOI18N
        head.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        labelShowDate.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowDate.setText("dd-MM-yyyy");
        head.add(labelShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        head.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 900, -1));

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        head.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 920, -1));

        txtSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        head.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 470, 30));

        btnSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("ค้นหา");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        head.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, 40));

        btnAll.setBackground(new java.awt.Color(255, 255, 255));
        btnAll.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        btnAll.setText("ดูทั้งหมด");
        btnAll.setBorderPainted(false);
        btnAll.setContentAreaFilled(false);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        head.add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 120, 40));

        tableBikeStatus.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        tableBikeStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBikeStatus);

        head.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 780, 170));

        labelRentId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelRentId.setText("รหัสการเช่า-คืน :");
        head.add(labelRentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        labelRentDate.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelRentDate.setText("วันที่เช่า :");
        head.add(labelRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        labelCitizenId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelCitizenId.setText("เลขประจำตัวประชาชน :");
        head.add(labelCitizenId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 160, -1));

        btnRent.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        btnRent.setText("เช่ารถ");
        btnRent.setBorderPainted(false);
        btnRent.setContentAreaFilled(false);
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });
        head.add(btnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        labelFName.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelFName.setText("ชื่อ :");
        head.add(labelFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        labelBikeId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelBikeId.setText("รหัสรถ :");
        head.add(labelBikeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        labelLName.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelLName.setText("นามสกุล :");
        head.add(labelLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        labelTel.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelTel.setText("หมายเลขโทรศัพท์ :");
        head.add(labelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        labelReturnDate.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelReturnDate.setText("วันที่คืน :");
        head.add(labelReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        labelFee.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        labelFee.setText("ค่าเช่า :");
        head.add(labelFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        txtRentId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        head.add(txtRentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 157, -1));

        txtRentDate.setEditable(false);
        txtRentDate.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        txtRentDate.setText("          วันที่ปัจจุบัน");
        head.add(txtRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 157, -1));

        txtReturnDate.setEditable(false);
        txtReturnDate.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        txtReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnDateActionPerformed(evt);
            }
        });
        head.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 157, -1));

        txtFee.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        txtFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeeActionPerformed(evt);
            }
        });
        head.add(txtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 157, -1));

        txtTel.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        head.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 157, -1));

        txtLName.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        head.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 157, -1));

        txtFName.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        head.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 157, -1));

        txtCitizenId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        head.add(txtCitizenId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 157, -1));

        txtBikeId.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        txtBikeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBikeIdKeyReleased(evt);
            }
        });
        head.add(txtBikeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 157, -1));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuCusInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuIncome.setBorder(null);
        menuIncome.setText("รายได้");
        menuIncome.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuIncome);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
       // TODO add your handling code here:
       new FormMenuMain().show();
        dispose();
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
        new FormRent().show();
        dispose();
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRentActionPerformed

    private void txtReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnDateActionPerformed

    private void txtFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeeActionPerformed

    private void txtBikeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBikeIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBikeIdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel head;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBikeId;
    private javax.swing.JLabel labelCitizenId;
    private javax.swing.JLabel labelFName;
    private javax.swing.JLabel labelFee;
    private javax.swing.JLabel labelLName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelRentDate;
    private javax.swing.JLabel labelRentId;
    private javax.swing.JLabel labelReturnDate;
    private javax.swing.JLabel labelShowDate;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JLabel labelTel;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuIncome;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tableBikeStatus;
    private javax.swing.JTextField txtBikeId;
    private javax.swing.JTextField txtCitizenId;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtRentDate;
    private javax.swing.JTextField txtRentId;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
